#!/usr/bin/env python
import os
import commands
import sys

def d(tuple):
    out = tuple[1]
    if out:
         print out

def die(msg):
    """Quit and provide error message"""
    print msg
    sys.exit(1)

def main(args):
    """Call dd and mklab5fs on an existing file"""
    fn = args[0]
    of = "of=%s" % fn
    sz = 1024
    d(commands.getstatusoutput("dd if=/dev/zero %s bs=%s count=1048576" % (of, sz)))
    d(commands.getstatusoutput("./mklab5fs %s" % fn))
    return 0

if __name__ == "__main__":
    if len(sys.argv) != 2:
      die("Please provide one argument:\n./newhd <dev>")
    args = sys.argv[1:]
    sys.exit(main(args))
